name: .NET Core
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build linux-x64
      run: dotnet publish -r linux-x64 -c Release -f netcoreapp3.1 /p:PublishTrimmed=true /p:PublishSingleFile=true  
    - name: Archive publish linux-x64 artifacts
      uses: actions/upload-artifact@v1
      with:
        name: FuzzyToDo_linux-x64
        path: FuzzyToDo/bin/Release/netcoreapp3.1/linux-x64/publish
    - name: Build linux-arm
      run: dotnet publish ./FuzzyToDo/FuzzyToDo.csproj -r linux-arm -c Release -f netcoreapp3.1 /p:PublishTrimmed=true /p:PublishSingleFile=true  
    - name: Archive publish linux-arm artifacts
      uses: actions/upload-artifact@v1
      with:
        name: FuzzyToDo_linux-arm
        path: FuzzyToDo/bin/Release/netcoreapp3.1/linux-arm/publish
    - name: Build win10-x64
      run: dotnet publish ./FuzzyToDo/FuzzyToDo.csproj -r win10-x64 -c Release -f netcoreapp3.1 /p:PublishTrimmed=true /p:PublishSingleFile=true  
    - name: Archive publish win10-x64 artifacts
      uses: actions/upload-artifact@v1
      with:
        name: FuzzyToDo_win10-x64
        path: FuzzyToDo/bin/Release/netcoreapp3.1/win10-x64/publish
