name: .NET Core
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}} 
    - name: Build linux-x64
      run: dotnet publish -r linux-x64 -c Release -f netcoreapp3.1 --self-contained=true 
    - name: Zip
      run: zip FuzzyToDo-linux-x64 FuzzyToDo/bin/Release/netcoreapp3.1/linux-x64/publish/*.*
    - name: Azure
      run: |
        ls -l
        export AZURE_STORAGE_ACCOUNT=githubbuilds
        export AZURE_STORAGE_KEY=${{secrets.storage_key}}
        export container_name=builds
        export blob_name=FuzzyToDo-linux-x64.zip
        export file_to_upload=FuzzyToDo-linux-x64.zip
        echo "Uploading the file..."
        az storage blob upload --container-name $container_name --file $file_to_upload --name $blob_name  
